sudo: required
dist: trusty
language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8
node_js:
  - 10
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 6.9.5

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  # - npm run test:unit
  - npm run test:e2e

deploy:
  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:master
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:development
    skip_cleanup: true
    on:
      branch: develop
