language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  - npm run test:unit

deploy:
  - provider: script
    script: firebase deploy --token $PRODUCTION_FIREBASE_TOKEN --only hosting:master
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: firebase deploy --token $PRODUCTION_FIREBASE_TOKEN --only hosting:develop
    skip_cleanup: true
    on:
      branch: develop
