language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  - npm run test:unit

deploy:
  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:master
    skip_cleanup: true
    # token:
    #  secure:
    # project: "britecore-codingtest"
    on:
      branch: master

  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:development
    skip_cleanup: true
    # token:
    #  secure: $PRODUCTION_FIREASE_TOKEN
    # project: "britecore-testing"
    on:
      branch: develop
