language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  - npm run test:unit

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $PRODUCTION_FIREBASE_TOKEN
    project: "britecore-codingtest"
    on:
      branch: master

  - provider: firebase
    skip_cleanup: true
    token:
      secure: $PRODUCTION_FIREBBASE_TOKEN
    project: "britecore-testing"
    on:
      branch: develop
