language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  # - npm run test:unit
  - npm run test:e2e

deploy:
  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:master
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: firebase deploy --non-interactive --token $PRODUCTION_FIREBASE_TOKEN --only hosting:development
    skip_cleanup: true
    on:
      branch: develop
