language: node_js

node_js:
  - "node"

install:
  - npm install -g firebase-tools
  - npm install
  - npm run build

script:
  - npm run test:unit
  if: branch = master
    - firebase deploy --token $PRODUCTION_FIREBASE_TOKEN --only hosting:master

  if: branch = development
    - firebase deploy --token $PRODUCTION_FIREBASE_TOKEN --only hosting:development
  # 1/IpflK166johcPalilBkCOZfc4m1w1AuPjU9xKRW1ydU
